### ISSUE TITLE
Auto upload resampled images as soon as created

### ISSUE THREAD

**Issue by claire-ee** [fspringveldt/ss-easy-s3#4]
Is there a way to auto upload to S3 the resampled images?

**Comment by fspringveldt** [comment]
Possibly. I've had a quick look and see `Image_Cached` is responsible for the resampled image. I haven't tried this, but what about adding this to your mysite/_config/config.yml:
```yml
Image_Cached:
  extensions:
    - S3ImageExtension
```

Do let me know how this goes @claire-ee
